language: python
python:
- '3.5'
- '3.6'
before_install: pip install pipenv
install:
- pipenv install --dev
- pipenv install --dev coveralls
script:
- pipenv run make _test
- coveralls
deploy:
  provider: pypi
  user: cganterh
  password:
    secure: rP7aA4m5eVmoOFNeEss7BV8pLnpMrB2SW/LVScYTy7VQkkPh727GWqX7BnaZA4E8I4to4VByD3c+zQWKdxfKVnT8JIHHjz/wQBybhu5DWNHz9Fn0VFLHVbI2lq6aA4naHdHuL42yDuP8nXlQmNbP9uBb5HZQY2pQEFa9LfGj4+wulli3nABddHXn/LLFqe2dl89U+XRZJLQJd8aJjnJKpXu+cqEgG+5511svk5iJ95oy6GwXiVDPKwDi4QF/zwy13OtlRfqsrC+jLsx34Re9fS3o6d61It1bqDxSzWw8ZAtQ3hMOrhgMiPtNEACK/k2xXBXgOuCyluOG6KtNiCWWMRRUY2rN9uzIZGoKibM1iO8P42nczivJXh3yiLb+zNclThTCPZwxcKe5mxvHcZxggUxADDVOJodZly9+mHVHlXWi77aOMhg+miseGlQFMLGP10t7lJOXtEYs0BRVy722tSvYkj1Ihn0Ou4bzJRVdrH6YX134aojR0iPLHF8VtGU6mxmJo/BdfO4+Ie+mE7SOU5jbBcVFv3//nLKS/5iu96m3bwQEX4HJZx8tJD5E/Z7pJNbpJ9KrOavaevLD9IJTzXLU4eY5kUikfw8DgRQ41HpG+lOj0NE0pFLufkMYyEgKq09KK6LeB4QUm6iBnzlV7oDm4h85FEnbupuIWdEc5Xo=
  on:
    tags: true
    python: '3.5'
  distributions: sdist bdist_wheel
